# Simple Kubernetes Pod to deploy the app contained in mavewrick1/getting-started-k8s:1.0
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: mavewrick1/getting-started-k8s:1.0
      ports:
        - containerPort: 8080
